// File generated by 'bdfe -n -s 32-126 spleen-5x8.bdf'
// COMMENT /*
// COMMENT  * Spleen 5x8 2.1.0
// COMMENT  * Copyright (c) 2018-2024, Frederic Cambus
// COMMENT  * https://www.cambus.net/
// COMMENT  *
// COMMENT  * Created:      2018-08-08
// COMMENT  * Last Updated: 2021-03-10
// COMMENT  *
// COMMENT  * Spleen is released under the BSD 2-Clause license.
// COMMENT  * See LICENSE file for details.
// COMMENT  *
// COMMENT  * SPDX-License-Identifier: BSD-2-Clause
// COMMENT  */
// FONT -misc-spleen-medium-r-normal--8-80-72-72-C-50-ISO10646-1
// FONTBOUNDINGBOX 5 8 0 -1
// FONT_DESCENT 1
// FONT_ASCENT 7
// COPYRIGHT "Copyright (c) 2018-2024, Frederic Cambus"
// Converted Font Size 5x8

#pragma once

#include <stdint.h>

#define FONT_WIDTH 5
#define FONT_HEIGHT 8
#define FONT_COUNT 95

static uint8_t font_chars[FONT_COUNT][FONT_HEIGHT] =
{
    {
        // STARTCHAR SPACE
        // ENCODING 32
        // BBX 5 8 0 -1
        //   32 ' ' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x00, //   3|     |
        0x00, //   4|     |
        0x00, //   5|     |
        0x00, //   6|     |
        0x00, //   7|     |
    },
    {
        // STARTCHAR EXCLAMATION MARK
        // ENCODING 33
        // BBX 5 8 0 -1
        //   33 '!' |01234|
        0x20, //   0|  #  |
        0x20, //   1|  #  |
        0x20, //   2|  #  |
        0x20, //   3|  #  |
        0x20, //   4|  #  |
        0x00, //   5|     |
        0x20, //   6|  #  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR QUOTATION MARK
        // ENCODING 34
        // BBX 5 8 0 -1
        //   34 '"' |01234|
        0x50, //   0| # # |
        0x50, //   1| # # |
        0x50, //   2| # # |
        0x00, //   3|     |
        0x00, //   4|     |
        0x00, //   5|     |
        0x00, //   6|     |
        0x00, //   7|     |
    },
    {
        // STARTCHAR NUMBER SIGN
        // ENCODING 35
        // BBX 5 8 0 -1
        //   35 '#' |01234|
        0x00, //   0|     |
        0x50, //   1| # # |
        0xF8, //   2|#####|
        0x50, //   3| # # |
        0x50, //   4| # # |
        0xF8, //   5|#####|
        0x50, //   6| # # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DOLLAR SIGN
        // ENCODING 36
        // BBX 5 8 0 -1
        //   36 '$' |01234|
        0x20, //   0|  #  |
        0x70, //   1| ### |
        0xA0, //   2|# #  |
        0x60, //   3| ##  |
        0x30, //   4|  ## |
        0x30, //   5|  ## |
        0xE0, //   6|###  |
        0x20, //   7|  #  |
    },
    {
        // STARTCHAR PERCENT SIGN
        // ENCODING 37
        // BBX 5 8 0 -1
        //   37 '%' |01234|
        0x10, //   0|   # |
        0x90, //   1|#  # |
        0xA0, //   2|# #  |
        0x20, //   3|  #  |
        0x40, //   4| #   |
        0x50, //   5| # # |
        0x90, //   6|#  # |
        0x80, //   7|#    |
    },
    {
        // STARTCHAR AMPERSAND
        // ENCODING 38
        // BBX 5 8 0 -1
        //   38 '&' |01234|
        0x20, //   0|  #  |
        0x50, //   1| # # |
        0x50, //   2| # # |
        0x60, //   3| ##  |
        0xA8, //   4|# # #|
        0x90, //   5|#  # |
        0x68, //   6| ## #|
        0x00, //   7|     |
    },
    {
        // STARTCHAR APOSTROPHE
        // ENCODING 39
        // BBX 5 8 0 -1
        //   39 ''' |01234|
        0x20, //   0|  #  |
        0x20, //   1|  #  |
        0x20, //   2|  #  |
        0x00, //   3|     |
        0x00, //   4|     |
        0x00, //   5|     |
        0x00, //   6|     |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LEFT PARENTHESIS
        // ENCODING 40
        // BBX 5 8 0 -1
        //   40 '(' |01234|
        0x10, //   0|   # |
        0x20, //   1|  #  |
        0x40, //   2| #   |
        0x40, //   3| #   |
        0x40, //   4| #   |
        0x40, //   5| #   |
        0x20, //   6|  #  |
        0x10, //   7|   # |
    },
    {
        // STARTCHAR RIGHT PARENTHESIS
        // ENCODING 41
        // BBX 5 8 0 -1
        //   41 ')' |01234|
        0x40, //   0| #   |
        0x20, //   1|  #  |
        0x10, //   2|   # |
        0x10, //   3|   # |
        0x10, //   4|   # |
        0x10, //   5|   # |
        0x20, //   6|  #  |
        0x40, //   7| #   |
    },
    {
        // STARTCHAR ASTERISK
        // ENCODING 42
        // BBX 5 8 0 -1
        //   42 '*' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x90, //   2|#  # |
        0x60, //   3| ##  |
        0xF0, //   4|#### |
        0x60, //   5| ##  |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR PLUS SIGN
        // ENCODING 43
        // BBX 5 8 0 -1
        //   43 '+' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x20, //   2|  #  |
        0x20, //   3|  #  |
        0xF8, //   4|#####|
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR COMMA
        // ENCODING 44
        // BBX 5 8 0 -1
        //   44 ',' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x00, //   3|     |
        0x00, //   4|     |
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0x40, //   7| #   |
    },
    {
        // STARTCHAR HYPHEN-MINUS
        // ENCODING 45
        // BBX 5 8 0 -1
        //   45 '-' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x00, //   3|     |
        0xF0, //   4|#### |
        0x00, //   5|     |
        0x00, //   6|     |
        0x00, //   7|     |
    },
    {
        // STARTCHAR FULL STOP
        // ENCODING 46
        // BBX 5 8 0 -1
        //   46 '.' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x00, //   3|     |
        0x00, //   4|     |
        0x00, //   5|     |
        0x20, //   6|  #  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR SOLIDUS
        // ENCODING 47
        // BBX 5 8 0 -1
        //   47 '/' |01234|
        0x10, //   0|   # |
        0x10, //   1|   # |
        0x20, //   2|  #  |
        0x20, //   3|  #  |
        0x40, //   4| #   |
        0x40, //   5| #   |
        0x80, //   6|#    |
        0x80, //   7|#    |
    },
    {
        // STARTCHAR DIGIT ZERO
        // ENCODING 48
        // BBX 5 8 0 -1
        //   48 '0' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0xB0, //   3|# ## |
        0xD0, //   4|## # |
        0x90, //   5|#  # |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT ONE
        // ENCODING 49
        // BBX 5 8 0 -1
        //   49 '1' |01234|
        0x00, //   0|     |
        0x20, //   1|  #  |
        0x60, //   2| ##  |
        0x20, //   3|  #  |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT TWO
        // ENCODING 50
        // BBX 5 8 0 -1
        //   50 '2' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0x10, //   3|   # |
        0x60, //   4| ##  |
        0x80, //   5|#    |
        0xF0, //   6|#### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT THREE
        // ENCODING 51
        // BBX 5 8 0 -1
        //   51 '3' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0x20, //   3|  #  |
        0x10, //   4|   # |
        0x90, //   5|#  # |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT FOUR
        // ENCODING 52
        // BBX 5 8 0 -1
        //   52 '4' |01234|
        0x00, //   0|     |
        0x80, //   1|#    |
        0xA0, //   2|# #  |
        0xA0, //   3|# #  |
        0xF0, //   4|#### |
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT FIVE
        // ENCODING 53
        // BBX 5 8 0 -1
        //   53 '5' |01234|
        0x00, //   0|     |
        0xF0, //   1|#### |
        0x80, //   2|#    |
        0xE0, //   3|###  |
        0x10, //   4|   # |
        0x10, //   5|   # |
        0xE0, //   6|###  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT SIX
        // ENCODING 54
        // BBX 5 8 0 -1
        //   54 '6' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x80, //   2|#    |
        0xE0, //   3|###  |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT SEVEN
        // ENCODING 55
        // BBX 5 8 0 -1
        //   55 '7' |01234|
        0x00, //   0|     |
        0xF0, //   1|#### |
        0x90, //   2|#  # |
        0x10, //   3|   # |
        0x20, //   4|  #  |
        0x40, //   5| #   |
        0x40, //   6| #   |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT EIGHT
        // ENCODING 56
        // BBX 5 8 0 -1
        //   56 '8' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0x60, //   3| ##  |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR DIGIT NINE
        // ENCODING 57
        // BBX 5 8 0 -1
        //   57 '9' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x70, //   4| ### |
        0x10, //   5|   # |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR COLON
        // ENCODING 58
        // BBX 5 8 0 -1
        //   58 ':' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x20, //   3|  #  |
        0x00, //   4|     |
        0x00, //   5|     |
        0x20, //   6|  #  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR SEMICOLON
        // ENCODING 59
        // BBX 5 8 0 -1
        //   59 ';' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x20, //   3|  #  |
        0x00, //   4|     |
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0x40, //   7| #   |
    },
    {
        // STARTCHAR LESS-THAN SIGN
        // ENCODING 60
        // BBX 5 8 0 -1
        //   60 '<' |01234|
        0x00, //   0|     |
        0x10, //   1|   # |
        0x20, //   2|  #  |
        0x40, //   3| #   |
        0x40, //   4| #   |
        0x20, //   5|  #  |
        0x10, //   6|   # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR EQUALS SIGN
        // ENCODING 61
        // BBX 5 8 0 -1
        //   61 '=' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0xF0, //   3|#### |
        0x00, //   4|     |
        0xF0, //   5|#### |
        0x00, //   6|     |
        0x00, //   7|     |
    },
    {
        // STARTCHAR GREATER-THAN SIGN
        // ENCODING 62
        // BBX 5 8 0 -1
        //   62 '>' |01234|
        0x00, //   0|     |
        0x40, //   1| #   |
        0x20, //   2|  #  |
        0x10, //   3|   # |
        0x10, //   4|   # |
        0x20, //   5|  #  |
        0x40, //   6| #   |
        0x00, //   7|     |
    },
    {
        // STARTCHAR QUESTION MARK
        // ENCODING 63
        // BBX 5 8 0 -1
        //   63 '?' |01234|
        0x60, //   0| ##  |
        0x90, //   1|#  # |
        0x10, //   2|   # |
        0x20, //   3|  #  |
        0x40, //   4| #   |
        0x00, //   5|     |
        0x40, //   6| #   |
        0x00, //   7|     |
    },
    {
        // STARTCHAR COMMERCIAL AT
        // ENCODING 64
        // BBX 5 8 0 -1
        //   64 '@' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0xB0, //   3|# ## |
        0xB0, //   4|# ## |
        0x80, //   5|#    |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER A
        // ENCODING 65
        // BBX 5 8 0 -1
        //   65 'A' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0xF0, //   4|#### |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER B
        // ENCODING 66
        // BBX 5 8 0 -1
        //   66 'B' |01234|
        0x00, //   0|     |
        0xE0, //   1|###  |
        0x90, //   2|#  # |
        0xE0, //   3|###  |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0xE0, //   6|###  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER C
        // ENCODING 67
        // BBX 5 8 0 -1
        //   67 'C' |01234|
        0x00, //   0|     |
        0x70, //   1| ### |
        0x80, //   2|#    |
        0x80, //   3|#    |
        0x80, //   4|#    |
        0x80, //   5|#    |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER D
        // ENCODING 68
        // BBX 5 8 0 -1
        //   68 'D' |01234|
        0x00, //   0|     |
        0xE0, //   1|###  |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0xE0, //   6|###  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER E
        // ENCODING 69
        // BBX 5 8 0 -1
        //   69 'E' |01234|
        0x00, //   0|     |
        0x70, //   1| ### |
        0x80, //   2|#    |
        0xE0, //   3|###  |
        0x80, //   4|#    |
        0x80, //   5|#    |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER F
        // ENCODING 70
        // BBX 5 8 0 -1
        //   70 'F' |01234|
        0x00, //   0|     |
        0x70, //   1| ### |
        0x80, //   2|#    |
        0x80, //   3|#    |
        0xE0, //   4|###  |
        0x80, //   5|#    |
        0x80, //   6|#    |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER G
        // ENCODING 71
        // BBX 5 8 0 -1
        //   71 'G' |01234|
        0x00, //   0|     |
        0x70, //   1| ### |
        0x80, //   2|#    |
        0xB0, //   3|# ## |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER H
        // ENCODING 72
        // BBX 5 8 0 -1
        //   72 'H' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0x90, //   2|#  # |
        0xF0, //   3|#### |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER I
        // ENCODING 73
        // BBX 5 8 0 -1
        //   73 'I' |01234|
        0x00, //   0|     |
        0x70, //   1| ### |
        0x20, //   2|  #  |
        0x20, //   3|  #  |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER J
        // ENCODING 74
        // BBX 5 8 0 -1
        //   74 'J' |01234|
        0x00, //   0|     |
        0x70, //   1| ### |
        0x20, //   2|  #  |
        0x20, //   3|  #  |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0xC0, //   6|##   |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER K
        // ENCODING 75
        // BBX 5 8 0 -1
        //   75 'K' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0x90, //   2|#  # |
        0xE0, //   3|###  |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER L
        // ENCODING 76
        // BBX 5 8 0 -1
        //   76 'L' |01234|
        0x00, //   0|     |
        0x80, //   1|#    |
        0x80, //   2|#    |
        0x80, //   3|#    |
        0x80, //   4|#    |
        0x80, //   5|#    |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER M
        // ENCODING 77
        // BBX 5 8 0 -1
        //   77 'M' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0xF0, //   2|#### |
        0xF0, //   3|#### |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER N
        // ENCODING 78
        // BBX 5 8 0 -1
        //   78 'N' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0xD0, //   2|## # |
        0xD0, //   3|## # |
        0xB0, //   4|# ## |
        0xB0, //   5|# ## |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER O
        // ENCODING 79
        // BBX 5 8 0 -1
        //   79 'O' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER P
        // ENCODING 80
        // BBX 5 8 0 -1
        //   80 'P' |01234|
        0x00, //   0|     |
        0xE0, //   1|###  |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0xE0, //   4|###  |
        0x80, //   5|#    |
        0x80, //   6|#    |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER Q
        // ENCODING 81
        // BBX 5 8 0 -1
        //   81 'Q' |01234|
        0x00, //   0|     |
        0x60, //   1| ##  |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x60, //   6| ##  |
        0x30, //   7|  ## |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER R
        // ENCODING 82
        // BBX 5 8 0 -1
        //   82 'R' |01234|
        0x00, //   0|     |
        0xE0, //   1|###  |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0xE0, //   4|###  |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER S
        // ENCODING 83
        // BBX 5 8 0 -1
        //   83 'S' |01234|
        0x00, //   0|     |
        0x70, //   1| ### |
        0x80, //   2|#    |
        0x60, //   3| ##  |
        0x10, //   4|   # |
        0x10, //   5|   # |
        0xE0, //   6|###  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER T
        // ENCODING 84
        // BBX 5 8 0 -1
        //   84 'T' |01234|
        0x00, //   0|     |
        0xF8, //   1|#####|
        0x20, //   2|  #  |
        0x20, //   3|  #  |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER U
        // ENCODING 85
        // BBX 5 8 0 -1
        //   85 'U' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER V
        // ENCODING 86
        // BBX 5 8 0 -1
        //   86 'V' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x60, //   5| ##  |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER W
        // ENCODING 87
        // BBX 5 8 0 -1
        //   87 'W' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0xF0, //   4|#### |
        0xF0, //   5|#### |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER X
        // ENCODING 88
        // BBX 5 8 0 -1
        //   88 'X' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0x90, //   2|#  # |
        0x60, //   3| ##  |
        0x60, //   4| ##  |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER Y
        // ENCODING 89
        // BBX 5 8 0 -1
        //   89 'Y' |01234|
        0x00, //   0|     |
        0x90, //   1|#  # |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x70, //   4| ### |
        0x10, //   5|   # |
        0xE0, //   6|###  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN CAPITAL LETTER Z
        // ENCODING 90
        // BBX 5 8 0 -1
        //   90 'Z' |01234|
        0x00, //   0|     |
        0xF0, //   1|#### |
        0x10, //   2|   # |
        0x20, //   3|  #  |
        0x40, //   4| #   |
        0x80, //   5|#    |
        0xF0, //   6|#### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LEFT SQUARE BRACKET
        // ENCODING 91
        // BBX 5 8 0 -1
        //   91 '[' |01234|
        0x70, //   0| ### |
        0x40, //   1| #   |
        0x40, //   2| #   |
        0x40, //   3| #   |
        0x40, //   4| #   |
        0x40, //   5| #   |
        0x40, //   6| #   |
        0x70, //   7| ### |
    },
    {
        // STARTCHAR REVERSE SOLIDUS
        // ENCODING 92
        // BBX 5 8 0 -1
        //   92 '\' |01234|
        0x80, //   0|#    |
        0x80, //   1|#    |
        0x40, //   2| #   |
        0x40, //   3| #   |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0x10, //   6|   # |
        0x10, //   7|   # |
    },
    {
        // STARTCHAR RIGHT SQUARE BRACKET
        // ENCODING 93
        // BBX 5 8 0 -1
        //   93 ']' |01234|
        0x70, //   0| ### |
        0x10, //   1|   # |
        0x10, //   2|   # |
        0x10, //   3|   # |
        0x10, //   4|   # |
        0x10, //   5|   # |
        0x10, //   6|   # |
        0x70, //   7| ### |
    },
    {
        // STARTCHAR CIRCUMFLEX ACCENT
        // ENCODING 94
        // BBX 5 8 0 -1
        //   94 '^' |01234|
        0x00, //   0|     |
        0x20, //   1|  #  |
        0x50, //   2| # # |
        0x88, //   3|#   #|
        0x00, //   4|     |
        0x00, //   5|     |
        0x00, //   6|     |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LOW LINE
        // ENCODING 95
        // BBX 5 8 0 -1
        //   95 '_' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x00, //   3|     |
        0x00, //   4|     |
        0x00, //   5|     |
        0x00, //   6|     |
        0xF0, //   7|#### |
    },
    {
        // STARTCHAR GRAVE ACCENT
        // ENCODING 96
        // BBX 5 8 0 -1
        //   96 '`' |01234|
        0x40, //   0| #   |
        0x20, //   1|  #  |
        0x00, //   2|     |
        0x00, //   3|     |
        0x00, //   4|     |
        0x00, //   5|     |
        0x00, //   6|     |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER A
        // ENCODING 97
        // BBX 5 8 0 -1
        //   97 'a' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x60, //   2| ##  |
        0x10, //   3|   # |
        0x70, //   4| ### |
        0x90, //   5|#  # |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER B
        // ENCODING 98
        // BBX 5 8 0 -1
        //   98 'b' |01234|
        0x80, //   0|#    |
        0x80, //   1|#    |
        0xE0, //   2|###  |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0xE0, //   6|###  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER C
        // ENCODING 99
        // BBX 5 8 0 -1
        //   99 'c' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x70, //   2| ### |
        0x80, //   3|#    |
        0x80, //   4|#    |
        0x80, //   5|#    |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER D
        // ENCODING 100
        // BBX 5 8 0 -1
        //  100 'd' |01234|
        0x10, //   0|   # |
        0x10, //   1|   # |
        0x70, //   2| ### |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER E
        // ENCODING 101
        // BBX 5 8 0 -1
        //  101 'e' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x70, //   2| ### |
        0x90, //   3|#  # |
        0xF0, //   4|#### |
        0x80, //   5|#    |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER F
        // ENCODING 102
        // BBX 5 8 0 -1
        //  102 'f' |01234|
        0x30, //   0|  ## |
        0x40, //   1| #   |
        0x40, //   2| #   |
        0xE0, //   3|###  |
        0x40, //   4| #   |
        0x40, //   5| #   |
        0x40, //   6| #   |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER G
        // ENCODING 103
        // BBX 5 8 0 -1
        //  103 'g' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x70, //   2| ### |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x60, //   5| ##  |
        0x10, //   6|   # |
        0xE0, //   7|###  |
    },
    {
        // STARTCHAR LATIN SMALL LETTER H
        // ENCODING 104
        // BBX 5 8 0 -1
        //  104 'h' |01234|
        0x80, //   0|#    |
        0x80, //   1|#    |
        0xE0, //   2|###  |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER I
        // ENCODING 105
        // BBX 5 8 0 -1
        //  105 'i' |01234|
        0x00, //   0|     |
        0x20, //   1|  #  |
        0x00, //   2|     |
        0x60, //   3| ##  |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0x30, //   6|  ## |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER J
        // ENCODING 106
        // BBX 5 8 0 -1
        //  106 'j' |01234|
        0x00, //   0|     |
        0x20, //   1|  #  |
        0x00, //   2|     |
        0x20, //   3|  #  |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0xC0, //   7|##   |
    },
    {
        // STARTCHAR LATIN SMALL LETTER K
        // ENCODING 107
        // BBX 5 8 0 -1
        //  107 'k' |01234|
        0x80, //   0|#    |
        0x80, //   1|#    |
        0x90, //   2|#  # |
        0xA0, //   3|# #  |
        0xC0, //   4|##   |
        0xA0, //   5|# #  |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER L
        // ENCODING 108
        // BBX 5 8 0 -1
        //  108 'l' |01234|
        0x40, //   0| #   |
        0x40, //   1| #   |
        0x40, //   2| #   |
        0x40, //   3| #   |
        0x40, //   4| #   |
        0x40, //   5| #   |
        0x30, //   6|  ## |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER M
        // ENCODING 109
        // BBX 5 8 0 -1
        //  109 'm' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x90, //   2|#  # |
        0xF0, //   3|#### |
        0xF0, //   4|#### |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER N
        // ENCODING 110
        // BBX 5 8 0 -1
        //  110 'n' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0xE0, //   2|###  |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER O
        // ENCODING 111
        // BBX 5 8 0 -1
        //  111 'o' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x60, //   2| ##  |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER P
        // ENCODING 112
        // BBX 5 8 0 -1
        //  112 'p' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0xE0, //   2|###  |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0xE0, //   5|###  |
        0x80, //   6|#    |
        0x80, //   7|#    |
    },
    {
        // STARTCHAR LATIN SMALL LETTER Q
        // ENCODING 113
        // BBX 5 8 0 -1
        //  113 'q' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x70, //   2| ### |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x70, //   5| ### |
        0x10, //   6|   # |
        0x10, //   7|   # |
    },
    {
        // STARTCHAR LATIN SMALL LETTER R
        // ENCODING 114
        // BBX 5 8 0 -1
        //  114 'r' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x70, //   2| ### |
        0x90, //   3|#  # |
        0x80, //   4|#    |
        0x80, //   5|#    |
        0x80, //   6|#    |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER S
        // ENCODING 115
        // BBX 5 8 0 -1
        //  115 's' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x70, //   2| ### |
        0x80, //   3|#    |
        0x60, //   4| ##  |
        0x10, //   5|   # |
        0xE0, //   6|###  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER T
        // ENCODING 116
        // BBX 5 8 0 -1
        //  116 't' |01234|
        0x40, //   0| #   |
        0x40, //   1| #   |
        0xE0, //   2|###  |
        0x40, //   3| #   |
        0x40, //   4| #   |
        0x40, //   5| #   |
        0x30, //   6|  ## |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER U
        // ENCODING 117
        // BBX 5 8 0 -1
        //  117 'u' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x90, //   5|#  # |
        0x70, //   6| ### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER V
        // ENCODING 118
        // BBX 5 8 0 -1
        //  118 'v' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x60, //   5| ##  |
        0x60, //   6| ##  |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER W
        // ENCODING 119
        // BBX 5 8 0 -1
        //  119 'w' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0xF0, //   4|#### |
        0xF0, //   5|#### |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER X
        // ENCODING 120
        // BBX 5 8 0 -1
        //  120 'x' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x90, //   2|#  # |
        0x60, //   3| ##  |
        0x60, //   4| ##  |
        0x90, //   5|#  # |
        0x90, //   6|#  # |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LATIN SMALL LETTER Y
        // ENCODING 121
        // BBX 5 8 0 -1
        //  121 'y' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x90, //   2|#  # |
        0x90, //   3|#  # |
        0x90, //   4|#  # |
        0x70, //   5| ### |
        0x10, //   6|   # |
        0xE0, //   7|###  |
    },
    {
        // STARTCHAR LATIN SMALL LETTER Z
        // ENCODING 122
        // BBX 5 8 0 -1
        //  122 'z' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0xF0, //   2|#### |
        0x10, //   3|   # |
        0x20, //   4|  #  |
        0x40, //   5| #   |
        0xF0, //   6|#### |
        0x00, //   7|     |
    },
    {
        // STARTCHAR LEFT CURLY BRACKET
        // ENCODING 123
        // BBX 5 8 0 -1
        //  123 '{' |01234|
        0x30, //   0|  ## |
        0x40, //   1| #   |
        0x40, //   2| #   |
        0xC0, //   3|##   |
        0xC0, //   4|##   |
        0x40, //   5| #   |
        0x40, //   6| #   |
        0x30, //   7|  ## |
    },
    {
        // STARTCHAR VERTICAL LINE
        // ENCODING 124
        // BBX 5 8 0 -1
        //  124 '|' |01234|
        0x20, //   0|  #  |
        0x20, //   1|  #  |
        0x20, //   2|  #  |
        0x20, //   3|  #  |
        0x20, //   4|  #  |
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0x20, //   7|  #  |
    },
    {
        // STARTCHAR RIGHT CURLY BRACKET
        // ENCODING 125
        // BBX 5 8 0 -1
        //  125 '}' |01234|
        0xC0, //   0|##   |
        0x20, //   1|  #  |
        0x20, //   2|  #  |
        0x30, //   3|  ## |
        0x30, //   4|  ## |
        0x20, //   5|  #  |
        0x20, //   6|  #  |
        0xC0, //   7|##   |
    },
    {
        // STARTCHAR TILDE
        // ENCODING 126
        // BBX 5 8 0 -1
        //  126 '~' |01234|
        0x00, //   0|     |
        0x00, //   1|     |
        0x00, //   2|     |
        0x48, //   3| #  #|
        0xB0, //   4|# ## |
        0x00, //   5|     |
        0x00, //   6|     |
        0x00, //   7|     |
    },
};
